### ISSUE TITLE
ChefSpec matchers missing.

### ISSUE THREAD

**Issue by rodrigdav** [opscode-cookbooks/users#78]
The supermarket version of this cookbook which is 1.7.0 is missing the matchers for chefspec.  Any chance we could get a version with those in it?

**Comment by dblessing** [comment]
These matchers are in master. We just need a release to the Supermarket :) There are a lot of nice fixes going back over the past year that need released.

**Comment by rodrigdav** [comment]
Any idea when they will be released?  Or should I just get the master branch?

**Comment by dblessing** [comment]
Good question. I'm hoping a Chef maintainer will come along and release this soon.

**Comment by rodrigdav** [comment]
@jtimberman can you provide any help on how to get the supermarket version updated?

**Comment by jtimberman** [comment]
1.8.0 was released yesterday. https://github.com/opscode-cookbooks/users/commit/79563f635ae807a950985dbf51e5aa8f0032a11f

**Comment by rodrigdav** [comment]
@jtimberman thank you.
