### ISSUE TITLE
Please release changes

### ISSUE THREAD

**Issue by dblessing** [opscode-cookbooks/users#84]
There are some nice changes and bug fixes going back almost a year. Please cut a new release for the Supermarket. :smiley:

**Comment by dblessing** [comment]
@cwebberOps Sorry to ping you directly. Can you or someone else at Chef please take a look at this cookbook and cut a new release? It's been over a year and lots of recent issues have been addressed in master :+1: Thanks in advance.

**Comment by nathenharvey** [comment]
v.1.8.0 was just released to the Supermarket - http://supermarket.chef.io/cookbooks/users

**Comment by dblessing** [comment]
Thanks @nathanharvey. You rock.
